### PR TITLE
New image repo to avoid Docker Hub rate limit

### PR DESCRIPTION
**Pull request by liveaverage**
Signed-off-by: J.R. Morgan <liveaverage@gmail.com>

### CODE REVIEW

**Comment by liveaverage** [comment]
Just delivered a workshop with this content and it went perfect, minus Docker Hub rate limiting!

If Grafana was pushing official images to quay.io I would have referenced those, but unfortunately there's an open issue about this: https://github.com/grafana/grafana/issues/27677

There's an unofficial quay.io-hosted image referenced on that issue (https://quay.io/repository/app-sre/grafana) but I opted for registry.redhat.io since the image is vetted/tested. Ran through the monitoring exercises using the new images without any issue.

**Comment by danieloh30** [comment]
@liveaverage thanks for bringing this up. I wonder if you had the rate limit issue like below during the workshop:

ERROR: toomanyrequests: Too Many Requests.

OR

You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits.

**Comment by liveaverage** [comment]
It was the latter @danieloh30  -- just replicated:

```
Failed to pull image "grafana/grafana@sha256:d227b9b699da8a75d279f2dcb8d21b00ecdc15deaa8dd6516a6455a872fb731b": rpc error: code = Unknown desc = Error reading manifest sha256:d227b9b699da8a75d279f2dcb8d21b00ecdc15deaa8dd6516a6455a872fb731b in docker.io/grafana/grafana: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by danieloh30** [comment]
Ok. can you close this and recreate a PR to ocp-4.5 branch as well as updating the relevant screentshots in the guides?

**Comment by liveaverage** [comment]
absolutely!

**Pull request closed without merging**
